/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viwes;

import Class.Connect;
import Class.Article;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class JiArticle extends javax.swing.JInternalFrame {
    ArrayList<Article> list=new ArrayList<>();
    DefaultTableModel df;
    int pos;
    int h,w;
    

    /**
     * Creates new form JiArticle
     * @param h
     * @param w
     */
    public JiArticle(int h,int w) {
        initComponents();
        df=(DefaultTableModel) jTable1.getModel();
        //jLabel1.setVisible(false);
       // txtid.setVisible(false);
       this.w=w;
       this.h=h;
        setSize(w,h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtlibelle = new javax.swing.JTextField();
        txtQteStock = new javax.swing.JTextField();
        BtnModifier = new javax.swing.JButton();
        BtnAjouter = new javax.swing.JButton();
        BtnSupprimer = new javax.swing.JButton();

        setBorder(null);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Article", "Libelle ", "Qte Stock"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setText("Libelle :");

        jLabel3.setText("Qte Stock : ");

        BtnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Actions-edit-redo-icon.png"))); // NOI18N
        BtnModifier.setText("Modifer");
        BtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifierActionPerformed(evt);
            }
        });

        BtnAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button-Add-icon.png"))); // NOI18N
        BtnAjouter.setText("Ajouter ");
        BtnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjouterActionPerformed(evt);
            }
        });

        BtnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button-Delete-icon.png"))); // NOI18N
        BtnSupprimer.setText("Supprimer");
        BtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(124, 124, 124)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQteStock, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(BtnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(BtnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(BtnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtlibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQteStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnModifier)
                    .addComponent(BtnAjouter)
                    .addComponent(BtnSupprimer))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            // TODO add your handling code here:
            Connection con=Connect.seconnenter();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from Article");
            while(rs.next()){
                list.add(new Article(rs.getInt(1),rs.getString(2),rs.getInt(3)));
                df.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getInt(3)}); 
            }
        } catch (Exception ex) {
            Logger.getLogger(JiArticle.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void BtnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjouterActionPerformed
        try {
            // TODO add your handling code here:
            int id_article = 0;
            String libelle=txtlibelle.getText();
            int qte=Integer.parseInt(txtQteStock.getText());
            Connection con=Connect.seconnenter();
            PreparedStatement ps=con.prepareStatement("insert into article values(seq_idart.nextval,?,?)",new int[]{1});
            ps.setString(1,libelle);
            ps.setInt(2, qte);
            ps.executeUpdate();
            ResultSet rs=ps.getGeneratedKeys();
            if(rs.next()){
                id_article=rs.getInt(1);
            }
            Article a=new Article(id_article, libelle, qte);
            list.add(a);
            df.addRow(new Object[]{id_article,libelle,qte});
            JOptionPane.showMessageDialog(this,"Article Ajouter Avec Succes");
            clear();
        } catch (Exception ex) {
            Logger.getLogger(JiArticle.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Error");
        }
        
    }//GEN-LAST:event_BtnAjouterActionPerformed

    private void BtnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifierActionPerformed
        try {
            // TODO add your handling code here:
            int row=jTable1.getSelectedRow();
            int id_aticle=Integer.parseInt(df.getValueAt(row,0).toString());
            String libelle=txtlibelle.getText();
            int qte=Integer.parseInt(txtQteStock.getText());
            Connection con=Connect.seconnenter();
            PreparedStatement ps=con.prepareStatement("update article set libelle=?,qtestock=? where idart=?");
            ps.setString(1,libelle);
            ps.setInt(2, qte);
            ps.setInt(3,id_aticle);
            ps.executeUpdate();
            df.setValueAt(libelle,row,1);
            df.setValueAt(qte,row,2);
            JOptionPane.showMessageDialog(this,"Article Modifier Avec Succes");
            clear();
        } catch (Exception ex) {
            Logger.getLogger(JiArticle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnModifierActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        int id=Integer.parseInt(df.getValueAt(row, 0).toString());
        String libelle=df.getValueAt(row, 1).toString();
        int qte=Integer.parseInt(df.getValueAt(row, 2).toString());
        txtlibelle.setText(libelle);
        txtQteStock.setText(qte+"");
    }//GEN-LAST:event_jTable1MouseClicked

    private void BtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSupprimerActionPerformed
        try {
            // TODO add your handling code here:
            Article a=list.get(pos);
            Connection con=Connect.seconnenter();
            PreparedStatement ps=con.prepareStatement("delete from article where idart=?");
            ps.setInt(1, a.getId_art());
            ps.executeUpdate();
            list.remove(a);
              for(int i=0;i<jTable1.getRowCount();i++){
                if(Integer.parseInt(df.getValueAt(i,0).toString())==a.getId_art()){
                    df.removeRow(i);
                }
            }
               JOptionPane.showMessageDialog(this,"Article Supprimer Avec Succes");
               clear();
        } catch (Exception ex) {
            Logger.getLogger(JiArticle.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BtnSupprimerActionPerformed
    public void clear(){
        txtlibelle.setText(null);
        txtQteStock.setText(null);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAjouter;
    private javax.swing.JButton BtnModifier;
    private javax.swing.JButton BtnSupprimer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtQteStock;
    private javax.swing.JTextField txtlibelle;
    // End of variables declaration//GEN-END:variables
}
